"""add total_price to rentals

Revision ID: fe6a98a7e9af
Revises: 8514220c767d
Create Date: 2026-07-09 08:30:32.544579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a98a7e9af'
down_revision: Union[str, Sequence[str], None] = '8514220c767d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'total_price')
    # ### end Alembic commands ###
